# version: '3.8'

services:
  # Configuração do PostgreSQL
  postgres_db:
    image: postgres:latest
    container_name: teste-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: torneio_db
    ports:
      - "5433:5432"